app:
  server:
    port: 7005
  grpc:
    port: 7050
  database:
    host: localhost
    port: 5432
    name: SweTimeTracking
    schema: swetimetracking
    username: postgres
    password: 123456
  kafka:
    host: localhost
    port: 9092
  config:
    timezone: Asia/Ho_Chi_Minh